### ISSUE TITLE
Add verbose mode

### ISSUE THREAD

**Issue by magdeoz** [szorfein/getch#2]
Is there any way to add verbosity?
In a system like gentoo things are slow and you might think that the script got stuck

**Comment by szorfein** [comment]
Yes that's right, some command take time to complete, i can add a --verbose mode for people who like to see the system compile :)

**Comment by magdeoz** [comment]
I tried in a virtual machine in qemu and when starting it gives me a kernel panic


![Captura de pantalla_2020-09-18_11-59-15](https://user-images.githubusercontent.com/10053172/93624872-a10b9680-f9a6-11ea-89a4-bbf76213968a.png)

**Comment by szorfein** [comment]
The support work on a Virtualbox Guest but not yet for Qemu, can you post the output of 2 commands from the ISO?
+ lspci
+ lsmod

**Comment by magdeoz** [comment]
I have tried the new version and it gives me exactly the same problem

lspci :
00:00.0 Host bridge: Intel Corporation 82G33/G31/P35/P31 Express DRAM Controller
00:01.0 VGA compatible controller: Red Hat, Inc. QXL paravirtual graphic card (rev 05)
00:02.0 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:02.1 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:02.2 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:02.3 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:02.4 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:02.5 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:02.6 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:1b.0 Audio device: Intel Corporation 82801I (ICH9 Family) HD Audio Controller (rev 03)
00:1f.0 ISA bridge: Intel Corporation 82801IB (ICH9) LPC Interface Controller (rev 02)
00:1f.2 SATA controller: Intel Corporation 82801IR/IO/IH (ICH9R/DO/DH) 6 port SATA Controller [AHCI mode] (rev 02)
00:1f.3 SMBus: Intel Corporation 82801I (ICH9 Family) SMBus Controller (rev 02)
01:00.0 Ethernet controller: Red Hat, Inc. Virtio network device (rev 01)
02:00.0 USB controller: Red Hat, Inc. QEMU XHCI Host Controller (rev 01)
03:00.0 Communication controller: Red Hat, Inc. Virtio console (rev 01)
04:00.0 SCSI storage controller: Red Hat, Inc. Virtio block device (rev 01)
05:00.0 Unclassified device [00ff]: Red Hat, Inc. Virtio memory balloon (rev 01)
06:00.0 Unclassified device [00ff]: Red Hat, Inc. Virtio RNG (rev 01)

lsmod: 
[lsmod.txt](https://github.com/szorfein/getch/files/5250125/lsmod.txt)

**Comment by szorfein** [comment]
Thanks for the files, this will help me a lot. It should work for the next release.  
I will add virtio_balloon, virtio_console, net_failover and see if anything else is missing

**Comment by szorfein** [comment]
The problem seem coming from Grub, i was boot with the rescue console
```
set root=(hd0,2)
linux /boot/vmlinuz-5.4.60-gentoo root=/dev/sda2
boot
```
Ok, i will solve this easily ! [from the wiki](https://wiki.gentoo.org/wiki/Knowledge_Base:Unable_to_mount_root_fs)  
`Ensure that, if you use root=UUID=..., you have built an initramfs when configuring the bootloader, see "Configuring the linux kernel" of your installation handbook`.

**Comment by magdeoz** [comment]
I get this error
![Captura de pantalla_2020-09-23_10-56-33](https://user-images.githubusercontent.com/10053172/94038067-a80e1c80-fd8b-11ea-88ca-ef678e922ed0.png)

**Comment by szorfein** [comment]
Fixed, thank you !
