### ISSUE TITLE
Failure to install with problem opening /dev/false

### ISSUE THREAD

**Issue by oz123** [szorfein/getch#3]
Hi,

I was trying to test this gem in VM, but failed with the following error:

```
root@ubuntu:/home/ubuntu# getch -d vda 

Build Gentoo Linux with the following args:

	Lang: en_US
	Timezone: UTC
	Keymap: us
	Disk: vda
	Filesystem: ext4
	Username: false
	Encrypt: false
	Musl: false

	separate-boot disk: false
	separate-cache disk: false
	separate-home disk: false

Continue? (y,N) y

Partition and format disk vda, this will erase all data, continue? (y,N) y
I >>> 24 Exec: sgdisk -Z /dev/vda				[ ok ]
I >>> 27 Exec: wipefs --all /dev/vda				[ ok ]
I >>> 49 Exec: dd if=/dev/zero of=/dev/vda bs=1M count=100	[ ok ]
I >>> 45 Exec: sgdisk -n1:1M:+260M -t1:ef00 /dev/false		
D [5981] > Problem opening /dev/false for reading! Error is 2.

D [5981] > The specified file does not exist!

E > sgdisk -n1:1M:+260M -t1:ef00 /dev/false - pid 5993 exit 2	
F > Running sgdisk -n1:1M:+260M -t1:ef00 /dev/false
```

**Comment by szorfein** [comment]
Hi, 

Do you run the last getch-0.3.4 or the git version?  
And can you post the content of `/tmp/getch_devs.yaml`?

I'm currently testing installing Gentoo with QEMU and the last Void live iso image and no problem for create partition.

**Comment by oz123** [comment]
I can't post this file, but if it helps, I used ubuntu livecd.

**Comment by szorfein** [comment]
Which version of Ubuntu? i tested the last https://releases.ubuntu.com/kinetic/ubuntu-22.10-desktop-amd64.iso with no problem.

**Comment by oz123** [comment]
I used both of the latest LTS live installer, 22 and 20.

**Comment by szorfein** [comment]
Unfortunately i was unable to reproduce this, here are the steps i did.
Download and boot on the last [iso](https://releases.ubuntu.com/kinetic/ubuntu-22.10-desktop-amd64.iso)

1. Install ruby/gem `sudo apt-get install ruby-rubygems`
2. Install last version of Getch on the system

```sh
sudo gem install getch
sudo getch -v
Getch v0.3.5
```
3. Make sure the target disk is actually unused, umounted and install Gentoo

```sh
sudo getch -d sda
```

Thanks for the report

**Comment by szorfein** [comment]
Yeah, i've had this error today, for now, you only need to do a `getch -d vda --restart` to regenerate `/tmp/getch_devs.yaml`

**Comment by oz123** [comment]
I just tried again, and the bug still exists, however adding the flag `--restart` does the trick.
