### ISSUE TITLE
fail to install with lvm and encryption

### ISSUE THREAD

**Issue by oz123** [szorfein/getch#4]
```
ubuntu@ubuntu:~$ sudo getch --format ext4 --lvm --encrypt -d vda --restart
Initialize states
Init devs at /tmp/getch_devs.yaml

Build Gentoo Linux with the following args:

	Lang: en_US
	Timezone: UTC
	Keymap: us
	Disk: vda
	Filesystem: ext4
	Username: false
	Encrypt: true
	Musl: false

	separate-boot disk: false
	separate-cache disk: false
	separate-home disk: false

Continue? (y,N) y

Partition and format disk vda, this will erase all data, continue? (y,N) y
I >>> 24 Exec: sgdisk -Z /dev/vda				[ ok ]
I >>> 27 Exec: wipefs --all /dev/vda				[ ok ]
I >>> 49 Exec: dd if=/dev/zero of=/dev/vda bs=1M count=100	[ ok ]
I >>> 45 Exec: sgdisk -n1:1MiB:+1MiB -t1:ef02 /dev/vda		[ ok ]
I >>> 44 Exec: sgdisk -n2:0:+256MiB -t2:8309 /dev/vda		[ ok ]
I >>> 24 Exec: sgdisk -E /dev/vda				[ ok ]
I >>> 45 Exec: sgdisk -n3:0:52426751 -t3:8309 /dev/vda		[ ok ]
I >>> 34 Exec: blockdev --getpbsz /dev/vda2			[ ok ]
I >>> 31 Encrypting boot-luks > vda2...

WARNING!
========
This will overwrite data on /dev/vda2 irrevocably.

Are you sure? (Type 'yes' in capital letters): YES
Enter passphrase for /dev/vda2: 
Verify passphrase: 
I >>> 28 Opening boot-luks > vda2...
Enter passphrase for /dev/vda2: 
I >>> 28 Formating disk with ext4...
I >>> 47 Exec: mkfs.ext4 -F -b 512 /dev/mapper/boot-luks		
D [6103] > mkfs.ext4: invalid block size - 512

E > mkfs.ext4 -F -b 512 /dev/mapper/boot-luks - pid 6169 exit 1	
F > Running mkfs.ext4 -F -b 512 /dev/mapper/boot-luks
```

**Comment by oz123** [comment]
Comparing the output of an LVM installation without encryption, I suspect that the issue is that the code is listing all
devices under dev mapper, and then creates filesystem. However, boot-luks should be exluced from this list.

**Comment by szorfein** [comment]
Hi, thanks for the issue. Can you give me the version of Getch? if not try using the last :)

    >>> 47 Exec: mkfs.ext4 -F -b 512 /dev/mapper/boot-luks

The last version should not use `-b 512` for old disk. from [lib/mkfs.rb](https://github.com/szorfein/getch/blob/main/lib/mkfs.rb#L75)

```ruby
def mkfs_ext4(path)
  bs = Getch::Helpers.get_bs(path)
    if bs == '512'
      Getch::Command.new('mkfs.ext4', '-F', path)
    else
      Getch::Command.new('mkfs.ext4', '-F', '-b', bs, path)
    end
end
```

**Comment by oz123** [comment]
It's the last version from gem install. Happens also with git. 
In tried debugging this a bit. However, my ruby skills are very limited. 
Never the less, I have a feeling this could be the Gentoo Installer I've been looking for. So thanks for putting this for public usage.

**Comment by oz123** [comment]
Also, I don't think you should format 
 /dev/mapper/boot-luks, if there is LVM on top. Check my flags. 
When you have LVM you format each volume. Your code does that too.

**Comment by szorfein** [comment]
I don't have a 512 disk, it would be great to be able to do some tests with the previous code, all the test bellow work for me, it should depend of the ruby version installed i think....  

1. get the code: `git clone https://github.com/szorfein/getch`
2. `cd getch && $EDITOR lib/mkfs.rb` (line 75)

There are several method to check if a string match ...

test 1 - with match
```ruby
def mkfs_ext4(path)
  bs = Getch::Helpers.get_bs(path)
  if bs.match?(/^512/)
    Getch::Command.new('mkfs.ext4', '-F', path)
  else
    Getch::Command.new('mkfs.ext4', '-F', '-b', bs, path)
  end
end
```
test 2 -- with []

```ruby
def mkfs_ext4(path)
  bs = Getch::Helpers.get_bs(path)
  if bs['512']
    Getch::Command.new('mkfs.ext4', '-F', path)
  else
    Getch::Command.new('mkfs.ext4', '-F', '-b', bs, path)
  end
end
```
test 3 - with [/^xxx/]

```ruby
def mkfs_ext4(path)
  bs = Getch::Helpers.get_bs(path)
  if bs[/^512/]
    Getch::Command.new('mkfs.ext4', '-F', path)
  else
    Getch::Command.new('mkfs.ext4', '-F', '-b', bs, path)
  end
end
```
test 4 - without bs/if (the worse)

```ruby
def mkfs_ext4(path)
  Getch::Command.new('mkfs.ext4', '-F', path)
end
```

Save and relaunch Getch on each change:

3. `sudo ruby -I lib bin/getch --format ext4 --lvm --encrypt -d vda --restart`

You should see:

    >>> 47 Exec: mkfs.ext4 -F /dev/mapper/boot-luks

Instead of

    >>> 47 Exec: mkfs.ext4 -F -b 512 /dev/mapper/boot-luks

**Comment by szorfein** [comment]
The boot disk is encrypted here because it contain all the sensitive `luks-keys` for each disks used in the install.  
When the system boot, each disk used is decrypted via it's own luks-key to avoid to enter password twice, 

the /boot partition is the only one that is opened by a password with GRUB2 at boot time. with the option "GRUB_ENABLE_CRYPTODISK=y" >>/etc/default/grub

**Comment by oz123** [comment]
I see now. I thought that the boot disk encryption is a mistake. 
I am only testing this on KVM. I assume you can do the same to get a disk with bs=512.
Can try these tests later today.

**Comment by oz123** [comment]
Ah! I managed to fix this issue with my limited ruby skills. Feeling proud of myself.
There is another module that is responsible for formatting `/dev/mapper/boot-luks`. 
Even though the block size is 512, it does not work. So my patch was simply to let 
`mkfs.ext4` do it's thing without `bs`.

```
--- a/lib/luks.rb
+++ b/lib/luks.rb
@@ -110,7 +110,9 @@ module Luks
     # https://wiki.archlinux.org/title/Advanced_Format#File_systems
     def format_ext4
       @log.info "Formating disk with #{@format}...\n"
-      sh 'mkfs.ext4', '-F', '-b', @bs, "/dev/mapper/#{@luks_name}"
+      bs = Getch::Helpers.get_bs("/dev/mapper/#{@luks_name}")
+      @log.info "BS is #{bs}...\n"
+      sh 'mkfs.ext4', '-F', "/dev/mapper/#{@luks_name}"
     end
```
Finally, you might want to change this formatting to `-b 1024` per default as the man page of `mkfs.ext4` says:

```
-b block-size
              Specify the size of blocks in bytes.  Valid block-size values are powers of two from 1024 up to 65536 
```

Also, I am not expert on this matter at all, but reading a bit what others write on the subject it seems that it's really OK
to change this to 1024 or just leave it.
https://www.reddit.com/r/techsupport/comments/q2vf2l/my_old_hdd_block_size_is_512_bytes_but_ive_put/

**Comment by szorfein** [comment]
yeah nice, I completely forgot this part of the code, it formats in ext4 in 2 differents places... dawn, I try to correct that during the day (or tomorrow :)), thanks you  :+1:

**Comment by oz123** [comment]
Thank you for the quick fix!
